spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

auth:
  oauth:
    github:
      client_id: ${GITHUB_CLIENT_ID}
      redirect_uri: ${GITHUB_REDIRECT_URI}
      client_secret: ${GITHUB_CLIENT_SECRET}
      scope: ${GITHUB_SCOPE}

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

