spring:
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        highlight_sql: true

auth:
  oauth:
    github:
      client_id: ${GITHUB_CLIENT_ID}
      redirect_uri: ${GITHUB_REDIRECT_URI}
      client_secret: ${GITHUB_CLIENT_SECRET}
      scope: ${GITHUB_SCOPE}

  session:
    ttl: 3600

#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: TRACE

# sample
aws:
  s3:
    bucket: "bucket-name"
    image-path: "images/"  # 마지막 / 필수
    presigned-url-expires-minutes: 10

cors:
  allowedOrigins: "http://localhost:3000, http://localhost:8080"
